Evolution of 'restauration' organism
epfl-si/elements pull request #486
Opened 2020-12-11 15:13 UTC by alinekeller

**Edit form atoms**
- add inline layout for radio buttons and checkboxes
- create custom range slider atom

**Evolution of 'restauration' organism**
- improve tabs and filters layout
- improve mobile table layout
- add nutrimenu score filters and icons

2020-12-14 09:34 UTC, jdelasoie requested changes
Hello Aline,

Merci pour ce changement. 

J'y ai apposé une question et surtout de propositions d'ajout d'un retour à la ligne en fin de fichier.

Sinon :+1:

2020-12-14 09:34 UTC, jdelasoie commented on assets/components/atoms/range/range.js
> +  document.documentElement.classList.add('js');
Je n'ai pas trouvé l'utilité de cette classe. Y a-t-il une raison ?

2020-12-14 09:34 UTC, jdelasoie commented on assets/components/atoms/checkbox/checkbox.yml
>     Items list with checkboxes enable people to select some options, or none, or all. Use checkboxes for search options, selection in a form, policy acknowledgment, etc.
```suggestion
   Items list with checkboxes enable people to select some options, or none, or all. Use checkboxes for search options, selection in a form, policy acknowledgment, etc.

```

2020-12-14 09:34 UTC, jdelasoie commented on assets/components/atoms/checkbox/checkbox.scss
> +}
```suggestion
}

```

2020-12-14 09:34 UTC, jdelasoie commented on assets/components/atoms/radio/radio.yml
> +    notes:
```suggestion

```

2020-12-14 09:34 UTC, jdelasoie commented on assets/components/atoms/range/range.twig
> +</div>
```suggestion
</div>

```

2020-12-14 09:34 UTC, jdelasoie commented on assets/components/atoms/range/range.yml
> +  Custom range slider.
```suggestion
  Custom range slider.

```

2020-12-14 09:34 UTC, jdelasoie commented on assets/components/organisms/restauration/restauration.twig
> +</div>
```suggestion
</div>

```

2020-12-15 13:04 UTC, alinekeller commented on assets/components/atoms/range/range.js
> +  document.documentElement.classList.add('js');
Un oubli, je la retire.

2020-12-15 13:07 UTC, alinekeller commented
@jdelasoie Hello Julien,

J'ai retiré la fonction js qui ne servait plus à rien, et validé tes modifications. C'est tout bon de mon côté :)

2020-12-15 14:03 UTC, merged